// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8eSobFvG1Z11HH1IV4M5cgJbYRIQab-I',
    appId: '1:970473686718:web:cc97e27ac7021fa887c0ef',
    messagingSenderId: '970473686718',
    projectId: 'photomap-d6f41',
    authDomain: 'photomap-d6f41.firebaseapp.com',
    storageBucket: 'photomap-d6f41.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG4T6o5ZU2uRiushn5Tbb4hRAx0DQyeMw',
    appId: '1:970473686718:android:319baa857b76c2bf87c0ef',
    messagingSenderId: '970473686718',
    projectId: 'photomap-d6f41',
    storageBucket: 'photomap-d6f41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD4YBLOIwqhRI2uGb_F_9fPKRSyxG3lGI',
    appId: '1:970473686718:ios:d42dae2535dede1987c0ef',
    messagingSenderId: '970473686718',
    projectId: 'photomap-d6f41',
    storageBucket: 'photomap-d6f41.firebasestorage.app',
    iosBundleId: 'com.example.jdphotomap',
  );
}
