name: Code metrics

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check-unused-files:
    name: "Check for unused files"
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            $PUB_CACHE
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-


      - name: Get dependencies
        run: flutter pub get


      - name: Check for unused files
        run: bash ./scripts/unused_dart_files.sh
